### PR TITLE
Added instructions for ssh

### PR DESCRIPTION
**Pull request by bitgeeky**
Added detailed ssh instruction for debugging/troubleshooting purpose.
Can be viewed here: https://github.com/bitgeeky/atlas-examples/blob/ssh/troubleshooting/ssh.md

Please review. @KFishner  r ?

### CODE REVIEW

**Comment by ElijahCaine** [comment]
Adding an example similar to https://github.com/airpair/ntiered-aws-docker-terraform-guide/blob/edit/terraform/app-servers.tf#L7 to contextualize some of the lone code snippets would make this perfect. I had to do some experimentation and eventually had to ask @bitgeeky to get my keys working.

**Comment by KFishner** [comment]
Cool - @bitgeeky can you add an example aws_instance resource to close the loop?

**Comment by bitgeeky** [comment]
@ElijahCaine  Thanks for the suggestions.
@KFishner  Made the suggested changes please review. r ?

**Comment by KFishner** [comment]
great work @bitgeeky

**Pull request merged**
