### PR TITLE
Refactor examples to use same inputs and file structure

### PR DESCRIPTION
**Pull request by clstokes**
Per #70, refactoring Atlas examples to use same inputs and file structure (where possible).

### CODE REVIEW

**Comment by KFishner** [comment]
:+1:

**Comment by clstokes** [comment]
@bensojona @KFishner @mootpt could someone review my updates to the main [README](https://github.com/hashicorp/atlas-examples/blob/f-refactoring-inputs/README.md)? I feel comfortable with the updates to the examples configs, though you're welcome to review those too of course.

Again, the intent of these changes is to make it easy to try all of our examples with the same set of variables and commands.

**Comment by bensojona** [comment]
So I've [got a branch](https://github.com/hashicorp/atlas-examples/compare/f-aws-simple-example) that [overlaps some of this](https://github.com/hashicorp/atlas-examples/blob/27ad856bddedf66518afada7db50ee8a489c6a87/setup/general.md), some parts are similar to your setup section. I then just reference that file throughout my different project READMEs.

Not quite finished, but most of the way there.

Does this info make more sense in the general atlas-examples README, or within a setup folder?

**Comment by bensojona** [comment]
Maybe we can add each of the projects to the main README stating what they are and how they can be used.

**Comment by clstokes** [comment]
Yea, a "catalog" of sorts makes a lot of sense. I think I mentioned this in #70.

**Comment by KFishner** [comment]
README looks good :+1: 

I agree with the catalog approach as well - a quick sentence on each example to explain the service it deploys and maybe the tools used in the example (Consul, Packer, TF, Nomad, etc)

**Comment by clstokes** [comment]
@KFishner @bensojona one last ping for one of you to review my latest [README](https://github.com/hashicorp/atlas-examples/blob/f-refactoring-inputs/README.md) changes then I'll merge this.

**Comment by KFishner** [comment]
LGTM!

**Pull request merged**
