### PR TITLE
Haproxy drupal mysql

### PR DESCRIPTION
**Pull request by enxebre**
This is a Haproxy, drupal, mysql example based on the other examples in case you find it useful to add it to the examples.
Thanks!

### CODE REVIEW

**Comment by KFishner** [comment]
Looks great - thanks for this! :+1: 

The only slight nit is on the directory layout — rather than having separate ops folders for HAProxy, Apache, etc, you could reduce duplication by just having one master ops folder. Notice in the [LAMP example](https://github.com/hashicorp/atlas-examples/tree/master/LAMP/ops), it's just one ops folder and the resources are shared between configs, rather than separate /ops/haproxy, /ops/apache/, etc. 

Was there a reason you spread out the resources rather than consolidated?

**Comment by derek-adair** [comment]
personally i envision having template packer projects that resemble this format.  ive been toying around with different ways to include common files / scripts among packer templates that each have their own distinct dependencies.

Is there any way to layer packer templates in a way you might layer docker images?  I really hate the idea of relying on copy-pasta to stub out new projects.

**Comment by KFishner** [comment]
Yeah agreed @derek-adair. 

No way to layer Packer templates - right now the best way to reduce duplication and copy-pasta is using common scripts / configs

**Comment by enxebre** [comment]
Hi,
only reason that I chose this approach is that personally I like to see each packer folder as a self contained thing with no dependencies that could be reused across multiple projects but as you pointed it has the obvious drawback of duplication. I´ll modify the folder layout for sharing the files :)

**Comment by KFishner** [comment]
awesome sounds good! I'll review when it's ready

**Comment by enxebre** [comment]
So scritpts can be shared now

**Comment by derek-adair** [comment]
@KFishner are there any packer feature requests or perhaps a roadmap to minimize the pain points here?  I feel like these kinds of things will provide immense benefits and not looking into this would be a mistake.

I've filed a feature request for [build caching](https://github.com/mitchellh/packer/issues/1995), it seems like layering packer images could be related in some way... I'm honestly kindof shocked there isn't anyone else asking for these things.

Either way something to combine/inherit different templates, paired with a build cache would make me EVER so happy.

**Comment by derek-adair** [comment]
Sorry to flood the example repo, its just a *perfect* example of why build caching and template inheritance would be amazing in packer.

**Comment by KFishner** [comment]
@derek-adair definitely would be valuable. As you mentioned we have the details in the Packer repo, which we use as our public roadmap. We'll keep you updated there! Thanks again for the feedback

**Comment by KFishner** [comment]
Thanks @enxebre !! Merged.

**Pull request merged**
