### PR TITLE
Added example configuration to link Travis CI with ATLAS

### PR DESCRIPTION
**Pull request by bitgeeky**
This example shows how to link to Travis CI with ATLAS for continuous delivery of application code.
The configuration has been tested and all builds are passing.
ref: https://travis-ci.org/bitgeeky/travis-to-atlas

Code can also be found here https://github.com/bitgeeky/atlas-examples/tree/TravisCI/TravisCI for easy review.

Please review. @KFishner  r ?

### CODE REVIEW

**Comment by derek-adair** [comment]
If i'm not mistaken, this would be used in loo of vagrant push, right?

**Comment by KFishner** [comment]
@derek-adair correct! we're making sure Atlas works with existing dev workflows. Github example coming soon :)

@bitgeeky I'll review shortly

**Comment by KFishner** [comment]
I think just the readme and Travis config are necessary. 

Can you update the readme to just explain sending application code from Travis to Atlas? The infrastructure creation/update is detailed thoroughly elsewhere, which we can link to

**Comment by bitgeeky** [comment]
Updated pull with suggested changes.
Please review. @KFishner  r ?

**Comment by KFishner** [comment]
Looks good! I'm going to make some language updates to the readme in a separate PR

**Pull request merged**
