### PR TITLE
Added working Wordpress on AWS example configured with LAMP Stack.

### PR DESCRIPTION
**Pull request by bitgeeky**
This is a working example for deploying Wordpress Blog/Application on AWS using ATLAS.
Instructions can be found in the README file.

The actual application can be easily viewed at https://github.com/bitgeeky/atlas-examples/tree/wordpress-application/wordpress since github doesn't allow to view very large pull request and this example contains lots of default wordpress files.

On navigating to `<public_ip>/wordpress` it should show the default wordpress installation page like 
http://52.1.230.58/wordpress/wp-admin/install.php

@KFishner  r ?

### CODE REVIEW

**Comment by KFishner** [comment]
Works like a charm! 

The README needed some love though, when in doubt always over explain. This is what I'm thinking:
https://gist.github.com/KFishner/518f626f7b4735f559cb

**Comment by bitgeeky** [comment]
Sounds good :-)  Updated README file in a separate commit so that its easier to review. I'll rebase and squash the commit when the pull is ready to be merged.

Let me know if it looks good now. @KFishner  r ?

**Comment by KFishner** [comment]
looks good - rebase and merge away

**Comment by bitgeeky** [comment]
Rebased and squashed commits, ready for merge.

**Pull request merged**
