### PR TITLE
Added working Wordpress example configured with LAMP Stack.

### PR DESCRIPTION
**Pull request by bitgeeky**
This is a working example for deploying Wordpress Blog/Application on AWS using ATLAS.
Instructions can be found in the README file.

Here is live application tested using AWS and ATLAS http://52.0.37.116/wordpress/wp-admin/install.php

Please review. @KFishner  r ?

### CODE REVIEW

**Comment by KFishner** [comment]
Looks like you have all the Wordpress files _in the repo_. Instead of putting them in the repo, it's best if you download them and put them on the AMI as part of the Packer build process. 

For example, we do that with Consul:
https://github.com/hashicorp/atlas-examples/blob/master/LAMP/ops/scripts/base.sh#L9

Let me know if that makes sense

**Comment by bitgeeky** [comment]
@KFishner  Sounds good ! Will make the required changes :+1:

**Comment by bitgeeky** [comment]
I thought more on this, if we download the application during the AMI creation process, we will not need to use Vagrant anywhere in the process and the soul purpose of building the application and pushing the changes to ATLAS will get defeated since the user will never have the application in his local dev environment.

This is what I think is the most suitable way, so that things are clear although I agree its a lot messy to have all the application files within the repo.

Please let me know what you think on this, I'll then make the changes accordingly :-)

**Comment by derek-adair** [comment]
Yes, currently the workflow is a *little* unclear because atlas does not have the ability to build vagrant boxes, yet.  But this is coming soon i hear.  The conceptual problem you are having is probably due to that.  If you are not developing wordpress there is absolutely no need to use vagrant up, you kinda can just get by with packer / terraform and install plugins to your hearts content!

The idea here is to have packer pre-install all of your application dependencies into whatever format you desire.  This would mean all of the wordpress application files, and everything wordpress needs to run are baked into the ami, and you expose your "application" or "plugins" or wahtever you wordpress hooligans call them (apologies, its been a while since using WP, not sure of the exact use cae w/ Atlas + WordPress).

1) Build vagrant box of your choosing with packer [vagrant post-processer](https://packer.io/docs/post-processors/vagrant.html).
2) Build atlas_artifact.  This takes a little bit thinking because you need to rework your provisioners to install the stuff you wish to linked to the development environments.  Like say, a hello world index for an example repo like this.
3) Create "App".  (hello world).
4) Link app
5) Vagrant push triggers atlas_artifact to build, and is made available to whomever is deploying.

I feel like WordPress is not an app fit to take full advantage of the Atlas platform.  I'm not sure what it would look like to write WP extensions and deploy them via Atlas, I feel like WP has its on distribution network / installations etc.  You can probably use the Atlas workflow to bootstrap plugins.... again, not sure exactly what that would look like though.

@KFishner @sethvargo  let me know if any of this is off base, i kindof replied to this to re-affirm some of my perceptions of the Atlas workflow.

**Comment by KFishner** [comment]
thanks for the note @derek-adair 

Wordpress is a bit of an odd creature since there are so many configuration files. In this situation, everything should be in the /app side since they are actually changing the logic of the app. 
The /ops side should really only hold configurations that change how the application itself is deployed.

**Comment by bitgeeky** [comment]
As discussed made a new pull request with mysql and apache-php on different vm's, rest all remains same.
ref: https://github.com/hashicorp/atlas-examples/pull/23

**Pull request closed without merging**
